version: 0.2
phases:
  install:
    commands:
      - echo "Installing Node.js"
      - curl -sL https://rpm.nodesource.com/setup_22.x | bash -
      - yum install -y nodejs
      - node -v # Verify Node.js installation
      - npm -v # Verify npm installation
      - echo "Installing application dependencies"
      - npm install # Install dependencies
      - node -e "console.log('Running Node.js ' + process.version)"
      - echo "Installing Codedeploy agent"
      - sudo yum update
      - sudo yum install ruby
      - sudo yum install wget
      - cd /home/ec2-user
      - wget https://aws-codedeploy-us-east-1.s3.us-east-1.amazonaws.com/latest/install
      - chmod +x ./install
      - sudo ./install auto
      - systemctl start codedeploy-agent
      - npm install
  build:
    commands:
      - echo "Packaging application"
      - zip -r app.zip . # Package the application
    post_build:
      commands:
        - echo "Uploading packaged application to S3"
        - aws s3 cp app.zip s3://ci-cd-lab-bucket/
        - echo "Build completed and uploaded to S3"
artifacts:
  files:
    - app.zip
