version: 0.2
phases:
  install:
    commands:
      - echo "Installing Node.js"
      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
      - source ~/.bashrc
      - nvm install --lts
      - node -e "console.log('Running Node.js ' + process.version)"
      - echo "Installing Codedeploy agent"
      - sudo yum update
      - sudo yum install ruby
      - sudo yum install wget
      - cd /home/ec2-user
      - wget https://aws-codedeploy-us-east-1.s3.us-east-1.amazonaws.com/latest/install
      - chmod +x ./install
      - sudo ./install auto
      - systemctl start codedeploy-agent
      - npm install
  build:
    commands:
      - echo "Packaging application"
      - zip -r app.zip . # Package the application
    post_build:
      commands:
        - echo "Uploading packaged application to S3"
        - aws s3 cp app.zip s3://ci-cd-lab-bucket/
        - echo "Build completed and uploaded to S3"
artifacts:
  files:
    - '**/*'
