version: 0.2

phases:
  install:
    commands:
      - echo "Updating packages and installing Node.js"
      - yum update -y
      - curl -sL https://rpm.nodesource.com/setup_22.x | bash -
      - yum install -y nodejs # Install Node.js
      - node -v # Verify Node.js installation
      - npm -v # Verify npm installation
      - echo "Installing application dependencies"
      - npm install # Install dependencies
  build:
    commands:
      - echo "Packaging application"
      - zip -r app.zip . # Package the application
  post_build:
    commands:
      - echo "Build completed. Ready to upload artifacts."

artifacts:
  files:
    - '**/*' # Define the artifact to upload
