version: 0.2
phases:
  install:
    commands:
      - echo "Installing Node.js"
      - nvm install node
      - node -v
  pre_build:
    commands:
      - echo "Installing dependencies"
      - npm install
  build:
    commands:
      - echo "Running tests"
      - npm test
  post_build:
    commands:
      - echo "Packaging application"
      - npm run build
artifacts:
  files:
    - '**/*'
